options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'hashicorp/terraform:1.7.4'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init -reconfigure
        terraform apply -auto-approve
